---
- name: create sonarqube default security group
  ec2_group: 
    name: "{{ ec2_sg_name }}"
    description: Security Group for Sonarqube created by Ansible
    region: "{{ aws_region }}"
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 80
      to_port: 80
      cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: basic_firewall
- name: launch a new ec2 instance
  ec2:
    group: "{{ ec2_sg_name }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    wait: true
    region: "{{ aws_region }}"
    keypair: "{{ ec2_keypair }}"
    count: 1
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 50
        delete_on_termination: yes
    instance_tags:
      Name: default-sonarqube
  register: ec2
- name: wait for SSH to come up
  wait_for: 
    host: "{{ item.public_ip }}"
    port: 22
    state: started
  with_items: "{{ ec2.instances }}"
- name: add tags to instance
  ec2_tag:
    resource: "{{ item.id }}"
    region: "{{ aws_region }}"
    state: present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: sonarqube-base
      service: sonarqube
      version: 8.5.1