  
GRANT USAGE ON SCHEMA public TO sonar;
GRANT ALL PRIVILEGES ON SCHEMA public TO sonar;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sonar;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sonar;